import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/navbar";

import { AuthProvider } from "@/lib/auth-provider";
import { ThemeProvider } from "@/lib/theme-provider";

import { GeistSans } from "geist/font";
import { Container } from "@/components/layout/container";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <AuthProvider>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <Container>{children}</Container>
            <Toaster position="top-center" richColors />
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
